#index:
#    path: /
#    controller: App\Controller\DefaultController::index
weather_in_city:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController:cityAction
weather:
  path: /weather
  controller: App\Controller\WeatherController:homePage

app_logout:
  path: /logout
  methods: GET